// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFindHistory(arg1) {
  return window['go']['main']['App']['AddFindHistory'](arg1);
}

export function AddItem(arg1, arg2) {
  return window['go']['main']['App']['AddItem'](arg1, arg2);
}

export function AddReplaceHistory(arg1) {
  return window['go']['main']['App']['AddReplaceHistory'](arg1);
}

export function ApplyHosts() {
  return window['go']['main']['App']['ApplyHosts']();
}

export function CheckMigration() {
  return window['go']['main']['App']['CheckMigration']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearCmdHistory() {
  return window['go']['main']['App']['ClearCmdHistory']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ClearHostsHistory(arg1) {
  return window['go']['main']['App']['ClearHostsHistory'](arg1);
}

export function ClearTrashcan() {
  return window['go']['main']['App']['ClearTrashcan']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function DeleteFromTrashcan(arg1) {
  return window['go']['main']['App']['DeleteFromTrashcan'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DeleteHostsHistory(arg1) {
  return window['go']['main']['App']['DeleteHostsHistory'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function FindBy(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindBy'](arg1, arg2, arg3);
}

export function FocusWindow() {
  return window['go']['main']['App']['FocusWindow']();
}

export function GetAllConfig() {
  return window['go']['main']['App']['GetAllConfig']();
}

export function GetBasicData() {
  return window['go']['main']['App']['GetBasicData']();
}

export function GetCmdHistory(arg1) {
  return window['go']['main']['App']['GetCmdHistory'](arg1);
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDefaultDataDir() {
  return window['go']['main']['App']['GetDefaultDataDir']();
}

export function GetFinalContent() {
  return window['go']['main']['App']['GetFinalContent']();
}

export function GetFindHistory(arg1) {
  return window['go']['main']['App']['GetFindHistory'](arg1);
}

export function GetHistoryList() {
  return window['go']['main']['App']['GetHistoryList']();
}

export function GetHostsContent(arg1) {
  return window['go']['main']['App']['GetHostsContent'](arg1);
}

export function GetHostsHistory(arg1, arg2) {
  return window['go']['main']['App']['GetHostsHistory'](arg1, arg2);
}

export function GetI18n() {
  return window['go']['main']['App']['GetI18n']();
}

export function GetItem(arg1) {
  return window['go']['main']['App']['GetItem'](arg1);
}

export function GetLocale() {
  return window['go']['main']['App']['GetLocale']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetReplaceHistory(arg1) {
  return window['go']['main']['App']['GetReplaceHistory'](arg1);
}

export function GetSystemHosts() {
  return window['go']['main']['App']['GetSystemHosts']();
}

export function GetSystemHostsPath() {
  return window['go']['main']['App']['GetSystemHostsPath']();
}

export function GetTrashcanList() {
  return window['go']['main']['App']['GetTrashcanList']();
}

export function GetTreeList(arg1) {
  return window['go']['main']['App']['GetTreeList'](arg1);
}

export function ImportData(arg1) {
  return window['go']['main']['App']['ImportData'](arg1);
}

export function ImportDataFromURL(arg1) {
  return window['go']['main']['App']['ImportDataFromURL'](arg1);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function MigrateData() {
  return window['go']['main']['App']['MigrateData']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function MoveItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveItem'](arg1, arg2, arg3);
}

export function MoveToTrashcan(arg1) {
  return window['go']['main']['App']['MoveToTrashcan'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RefreshRemoteHosts(arg1) {
  return window['go']['main']['App']['RefreshRemoteHosts'](arg1);
}

export function ReplaceHostsContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReplaceHostsContent'](arg1, arg2, arg3);
}

export function RestoreFromTrashcan(arg1) {
  return window['go']['main']['App']['RestoreFromTrashcan'](arg1);
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function SetHostsContent(arg1, arg2) {
  return window['go']['main']['App']['SetHostsContent'](arg1, arg2);
}

export function SetList(arg1) {
  return window['go']['main']['App']['SetList'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function SetSystemHosts(arg1, arg2) {
  return window['go']['main']['App']['SetSystemHosts'](arg1, arg2);
}

export function ShowItemInFolder(arg1) {
  return window['go']['main']['App']['ShowItemInFolder'](arg1);
}

export function ToggleDevTools() {
  return window['go']['main']['App']['ToggleDevTools']();
}

export function ToggleItem(arg1, arg2) {
  return window['go']['main']['App']['ToggleItem'](arg1, arg2);
}

export function UpdateItem(arg1) {
  return window['go']['main']['App']['UpdateItem'](arg1);
}
